<a href="https://colab.research.google.com/github/pragya42/twitter-sentiment-analysis-logistic-regression/blob/main/sentiment_analysis_with_logistic_regression.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [67]:
import pandas as pd
import numpy as np
import os


# New Section

In [68]:
#from google.colab import drive
#drive.mount('/content/drive')

In [69]:
data = pd.read_csv("/content/drive/MyDrive/Colab Notebooks/archive/training.csv",encoding='latin-1')
#data = pd.read_csv(r"C:\Users\pagya\Downloads\archive\training.csv",encoding='latin-1')

In [70]:
data.shape

(1599999, 6)

In [71]:
data.columns

Index(['0', '1467810369', 'Mon Apr 06 22:19:45 PDT 2009', 'NO_QUERY',
       '_TheSpecialOne_',
       '@switchfoot http://twitpic.com/2y1zl - Awww, that's a bummer.  You shoulda got David Carr of Third Day to do it. ;D'],
      dtype='object')

In [72]:
df = (pd.DataFrame(data.columns)).transpose()

In [73]:
df

0           1                             2         3                4  \
0  0  1467810369  Mon Apr 06 22:19:45 PDT 2009  NO_QUERY  _TheSpecialOne_   

                                                   5  
0  @switchfoot http://twitpic.com/2y1zl - Awww, t...

In [74]:
data.columns=["",1,2,3,4,5]

In [75]:
data.append(df)

0           1                             2         3  \
0        NaN  1467810672  Mon Apr 06 22:19:49 PDT 2009  NO_QUERY   
1        NaN  1467810917  Mon Apr 06 22:19:53 PDT 2009  NO_QUERY   
2        NaN  1467811184  Mon Apr 06 22:19:57 PDT 2009  NO_QUERY   
3        NaN  1467811193  Mon Apr 06 22:19:57 PDT 2009  NO_QUERY   
4        NaN  1467811372  Mon Apr 06 22:20:00 PDT 2009  NO_QUERY   
...      ...         ...                           ...       ...   
1599995  NaN  2193601969  Tue Jun 16 08:40:49 PDT 2009  NO_QUERY   
1599996  NaN  2193601991  Tue Jun 16 08:40:49 PDT 2009  NO_QUERY   
1599997  NaN  2193602064  Tue Jun 16 08:40:49 PDT 2009  NO_QUERY   
1599998  NaN  2193602129  Tue Jun 16 08:40:50 PDT 2009  NO_QUERY   
0          0  1467810369  Mon Apr 06 22:19:45 PDT 2009  NO_QUERY   

                       4                                                  5  \
0          scotthamilton  is upset that he can't update his Facebook by ...   
1               mattycus  @Kenichan I dived many times for the ball. Man...   
2                ElleCTF    my whole body feels itchy and like its on fire    
3                 Karoli  @nationwideclass no, it's not behaving at all....   
4               joy_wolf                      @Kwesidei not the whole crew    
...                  ...                                                ...   
1599995      TheWDBoards  TheWDB.com - Very cool to hear old Walt interv...   
1599996           bpbabe  Are you ready for your MoJo Makeover? Ask me f...   
1599997     tinydiamondz  Happy 38th Birthday to my boo of alll time!!! ...   
1599998   RyanTrevMorris  happy #charitytuesday @theNSPCC @SparksCharity...   
0        _TheSpecialOne_  @switchfoot http://twitpic.com/2y1zl - Awww, t...   

              
0        0.0  
1        0.0  
2        0.0  
3        0.0  
4        0.0  
...      ...  
1599995  4.0  
1599996  4.0  
1599997  4.0  
1599998  4.0  
0        NaN  

[1600000 rows x 7 columns]

In [76]:
data = data[["",5]]

In [77]:
data.columns= ["y","tweet"]

In [78]:
data

y                                              tweet
0        0  is upset that he can't update his Facebook by ...
1        0  @Kenichan I dived many times for the ball. Man...
2        0    my whole body feels itchy and like its on fire 
3        0  @nationwideclass no, it's not behaving at all....
4        0                      @Kwesidei not the whole crew 
...     ..                                                ...
1599994  4  Just woke up. Having no school is the best fee...
1599995  4  TheWDB.com - Very cool to hear old Walt interv...
1599996  4  Are you ready for your MoJo Makeover? Ask me f...
1599997  4  Happy 38th Birthday to my boo of alll time!!! ...
1599998  4  happy #charitytuesday @theNSPCC @SparksCharity...

[1599999 rows x 2 columns]

In [79]:
data = data.sample(800000)
data = data.reset_index(drop = "True")

In [80]:
from nltk.corpus import stopwords 
from nltk.tokenize import word_tokenize 
  
#sentence = "Machine Learning is cool!"
def preprocessing(sentence):
    ## lowercase 
    sentence = sentence.lower()
    # punctuation
    import string
    regular_punct = list(string.punctuation)
    for punc in regular_punct:
        if punc in sentence:
            sentence = sentence.replace(punc, ' ')

    #stopwords        
    stop_words = set(stopwords.words('english')) 

    #tokenisation
    word_tokens = word_tokenize(sentence)
  
    filtered_sentence = [w for w in word_tokens if not w in stop_words] 
    ##stemming
    from nltk.stem import PorterStemmer
    ps = PorterStemmer()
    final = []
    for word in filtered_sentence:
        final.append(ps.stem(word))
    #print(ps.stem(word)) 
    #print(final)
    return final

In [81]:
import string
(string.punctuation)

'!"#$%&\'()*+,-./:;<=>?@[\\]^_`{|}~'

In [82]:
import nltk
nltk.download('punkt')
nltk.download('stopwords')

[nltk_data] Downloading package punkt to /root/nltk_data...
[nltk_data]   Package punkt is already up-to-date!
[nltk_data] Downloading package stopwords to /root/nltk_data...
[nltk_data]   Package stopwords is already up-to-date!


True

In [83]:
data["tweets"] = data["tweet"].apply(preprocessing)

In [84]:
data["tweets"]

0                       [margi, haha, creo, xd, oook, love]
1                [mileycyru, that, great, idea, darn, cant]
2         [go, bed, get, away, hubbi, davekerb, day, ya,...
3            [hear, thunderrrr, storm, someon, come, cuddl]
4                            [shower, go, meet, hs, friend]
                                ...                        
799995    [congrat, maxin, reach, 40, karma, chang, crea...
799996    [wow, 12, follow, less, 30, min, twittergett, ...
799997                [serenetan, got, leh, bright, bright]
799998          [princesssuperc, london, want, go, seeeeee]
799999    [franni, wow, ninja, least, readi, worship, le...
Name: tweets, Length: 800000, dtype: object

In [85]:
#vocabulary
# Creating a Dictionary
vocab = set(data["tweets"][0])
for i in range(1,len(data)):
    #print (i)
    for a in data["tweets"][i] :
        vocab.add(a)
    
    
    

In [86]:
#vocab

In [87]:
#feature extraction
#from sklearn.feature_extraction.text import CountVectorizer

# Create CountVectorizer, which create bag-of-words model.
# stop_words : Specify language to remove stopwords. 
#vectorizer = CountVectorizer(stop_words='english')

# Learn vocabulary in sentences. 
#vectorizer.fit(data["tweet"])

# Get dictionary. 
#vectorizer.get_feature_names()



In [88]:
df = pd.DataFrame(vocab)


In [89]:
df.index =   df[0]

In [90]:
df["pos"]=0
df["neg"]=0
df

0  pos  neg
0                                     
t13                      t13    0    0
xt1nam                xt1nam    0    0
thebluebeet      thebluebeet    0    0
liencam              liencam    0    0
chach13              chach13    0    0
...                      ...  ...  ...
frostvalley      frostvalley    0    0
fnalv                  fnalv    0    0
arcanedollfac  arcanedollfac    0    0
sharl                  sharl    0    0
willsexi            willsexi    0    0

[383566 rows x 3 columns]

In [91]:
for i in range(0,len(data)):
    print(i)
    for a in data["tweets"][i]:
        if data["y"][i] == 4 :
            df["pos"][a]= df["pos"][a]+1
        else:
            df["neg"][a]= df["neg"][a]+1
    
    

0
1
2
3
4
5
6
7
8
9
10
11
12
13
14
15
16
17
18
19
20
21
22
23
24
25
26
27
28
29
30
31
32
33
34
35
36
37
38
39
40
41
42
43
44
45
46
47
48
49
50
51
52
53
54
55
56
57
58
59
60
61


/usr/local/lib/python3.7/dist-packages/ipykernel_launcher.py:5: SettingWithCopyWarning: 
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  """
/usr/local/lib/python3.7/dist-packages/ipykernel_launcher.py:7: SettingWithCopyWarning: 
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  import sys


Streaming output truncated to the last 5000 lines.
795000
795001
795002
795003
795004
795005
795006
795007
795008
795009
795010
795011
795012
795013
795014
795015
795016
795017
795018
795019
795020
795021
795022
795023
795024
795025
795026
795027
795028
795029
795030
795031
795032
795033
795034
795035
795036
795037
795038
795039
795040
795041
795042
795043
795044
795045
795046
795047
795048
795049
795050
795051
795052
795053
795054
795055
795056
795057
795058
795059
795060
795061
795062
795063
795064
795065
795066
795067
795068
795069
795070
795071
795072
795073
795074
795075
795076
795077
795078
795079
795080
795081
795082
795083
795084
795085
795086
795087
795088
795089
795090
795091
795092
795093
795094
795095
795096
795097
795098
795099
795100
795101
795102
795103
795104
795105
795106
795107
795108
795109
795110
795111
795112
795113
795114
795115
795116
795117
795118
795119
795120
795121
795122
795123
795124
795125
795126
795127
795128
795129
795130
795131
795132
795133
795134
7951

In [92]:
data["pos"] = 0
data["neg"] = 0
data

y                                              tweet  \
0       4   @so_margie haha no creo xD... oook  love you too   
1       0   @mileycyrus thats a great idea. :] darn i cant.    
2       4  Going to bed and then off to my get-away with ...   
3       0  i hear thunderrrr. it's about to storm.  someo...   
4       4         will shower and go out to meet HS friends    
...    ..                                                ...   
799995  4  Congrats Maxine for reaching 40 Karma!! can ch...   
799996  4  Wow 12 followers in less than 30 mins! twitter...   
799997  4                @serenetan got leh...bright bright    
799998  0  @PrincessSuperC WERE YOU IN LONDON:O I wanted ...   
799999  4  @frannis wow my ninja! at least you'll be read...   

                                                   tweets  pos  neg  
0                     [margi, haha, creo, xd, oook, love]    0    0  
1              [mileycyru, that, great, idea, darn, cant]    0    0  
2       [go, bed, get, away, hubbi, davekerb, day, ya,...    0    0  
3          [hear, thunderrrr, storm, someon, come, cuddl]    0    0  
4                          [shower, go, meet, hs, friend]    0    0  
...                                                   ...  ...  ...  
799995  [congrat, maxin, reach, 40, karma, chang, crea...    0    0  
799996  [wow, 12, follow, less, 30, min, twittergett, ...    0    0  
799997              [serenetan, got, leh, bright, bright]    0    0  
799998        [princesssuperc, london, want, go, seeeeee]    0    0  
799999  [franni, wow, ninja, least, readi, worship, le...    0    0  

[800000 rows x 5 columns]

In [93]:
for i in range(0,len(data)):
    print(i)
    for a in data["tweets"][i]:
        data["pos"][i]=data["pos"][i]+df["pos"][a]
        data["neg"][i]=data["neg"][i]+df["neg"][a]
        
        
        #if data["y"][i] == 4 :
         #   df["pos"][a]= df["pos"][a]+1
        #else:
         #   df["neg"][a]= df["neg"][a]+1
    

0
1
2
3
4
5
6
7
8
9
10
11
12
13
14
15
16
17
18
19
20
21
22
23
24
25
26
27
28
29

/usr/local/lib/python3.7/dist-packages/ipykernel_launcher.py:4: SettingWithCopyWarning: 
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  after removing the cwd from sys.path.
/usr/local/lib/python3.7/dist-packages/ipykernel_launcher.py:5: SettingWithCopyWarning: 
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  """


Streaming output truncated to the last 5000 lines.
795000
795001
795002
795003
795004
795005
795006
795007
795008
795009
795010
795011
795012
795013
795014
795015
795016
795017
795018
795019
795020
795021
795022
795023
795024
795025
795026
795027
795028
795029
795030
795031
795032
795033
795034
795035
795036
795037
795038
795039
795040
795041
795042
795043
795044
795045
795046
795047
795048
795049
795050
795051
795052
795053
795054
795055
795056
795057
795058
795059
795060
795061
795062
795063
795064
795065
795066
795067
795068
795069
795070
795071
795072
795073
795074
795075
795076
795077
795078
795079
795080
795081
795082
795083
795084
795085
795086
795087
795088
795089
795090
795091
795092
795093
795094
795095
795096
795097
795098
795099
795100
795101
795102
795103
795104
795105
795106
795107
795108
795109
795110
795111
795112
795113
795114
795115
795116
795117
795118
795119
795120
795121
795122
795123
795124
795125
795126
795127
795128
795129
795130
795131
795132
795133
795134
7951

In [94]:
#vector = vectorizer.transform(sentences)
#vector_spaces = vector.toarray()
data

y                                              tweet  \
0       4   @so_margie haha no creo xD... oook  love you too   
1       0   @mileycyrus thats a great idea. :] darn i cant.    
2       4  Going to bed and then off to my get-away with ...   
3       0  i hear thunderrrr. it's about to storm.  someo...   
4       4         will shower and go out to meet HS friends    
...    ..                                                ...   
799995  4  Congrats Maxine for reaching 40 Karma!! can ch...   
799996  4  Wow 12 followers in less than 30 mins! twitter...   
799997  4                @serenetan got leh...bright bright    
799998  0  @PrincessSuperC WERE YOU IN LONDON:O I wanted ...   
799999  4  @frannis wow my ninja! at least you'll be read...   

                                                   tweets     pos     neg  
0                     [margi, haha, creo, xd, oook, love]   42868   16500  
1              [mileycyru, that, great, idea, darn, cant]   21313   15554  
2       [go, bed, get, away, hubbi, davekerb, day, ya,...  107431  122270  
3          [hear, thunderrrr, storm, someon, come, cuddl]   14824   17706  
4                          [shower, go, meet, hs, friend]   40994   48526  
...                                                   ...     ...     ...  
799995  [congrat, maxin, reach, 40, karma, chang, crea...   50677   29000  
799996  [wow, 12, follow, less, 30, min, twittergett, ...   68730   43098  
799997              [serenetan, got, leh, bright, bright]   17013   20051  
799998        [princesssuperc, london, want, go, seeeeee]   39075   60460  
799999  [franni, wow, ninja, least, readi, worship, le...   13449   14315  

[800000 rows x 5 columns]

In [95]:
data1 = data[["y","pos","neg"]]

In [96]:
#for i, v in zip(sentences, vector_spaces):#
    #print(i)
    #print(v)

In [97]:
## building vocabulary
from sklearn.model_selection import train_test_split
X = data1[["pos","neg"]]
y= data1[["y"]]
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.33, random_state=42)

In [98]:
from sklearn.preprocessing import StandardScaler
from sklearn.linear_model import LogisticRegression
from sklearn.pipeline import Pipeline
from sklearn.metrics import roc_curve, roc_auc_score, classification_report, accuracy_score, confusion_matrix 
import seaborn as sns
import matplotlib.pyplot as plt

scaler = StandardScaler()
lr = LogisticRegression()
model1 = Pipeline([('standardize', scaler),('log_reg', lr)])

In [99]:
model1.fit(X_train, y_train.values.ravel())

Pipeline(steps=[('standardize', StandardScaler()),
                ('log_reg', LogisticRegression())])

In [107]:
y_train_hat = model1.predict(X_train)
y_train_hat_probs = model1.predict_proba(X_train)[:,1]

train_accuracy = accuracy_score(y_train, y_train_hat)*100
train_auc_roc = roc_auc_score(y_train, y_train_hat_probs)*100

print('Confusion matrix:\n', confusion_matrix(y_train, y_train_hat))

print('Training AUC: %.4f %%' % train_auc_roc)

print('Training accuracy: %.4f %%' % train_accuracy)

Confusion matrix:
 [[188227  79597]
 [ 82951 185225]]
Training AUC: 74.6290 %
Training accuracy: 69.6739 %


In [101]:
y_test_hat = model1.predict(X_test)
y_test_hat_probs = model1.predict_proba(X_test)[:,1]

test_accuracy = accuracy_score(y_test, y_test_hat)*100
test_auc_roc = roc_auc_score(y_test, y_test_hat_probs)*100

print('Confusion matrix:\n', confusion_matrix(y_test, y_test_hat))

print('Testing AUC: %.4f %%' % test_auc_roc)

print('Testing accuracy: %.4f %%' % test_accuracy) 

Confusion matrix:
 [[92828 39419]
 [40376 91377]]
Testing AUC: 74.7727 %
Testing accuracy: 69.7746 %


In [102]:
y_test_hat_probs

array([0.09304414, 0.50844057, 0.51277507, ..., 0.62172688, 0.52848483,
       0.61027419])

In [103]:
# normal sentence output 
sen = "If you're not a happy cool german spy"
sen = preprocessing(sen)
chk = pd.DataFrame([[0,0]],columns = ["pos","neg"])
print(chk)


   pos  neg
0    0    0


In [104]:
chk
for a in sen:
    chk["pos"][0]=chk["pos"][0]+df["pos"][a]
    chk["neg"][0]=chk["neg"][0]+df["neg"][a]

In [105]:
chk

pos   neg
0  16308  5699

In [106]:
model1.predict(chk)

array([4])